config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :contacts
  resources :users
  root "contacts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_paper_trail
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :cellphone, :email, :birthdate, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role_id: {
    admin: 1,
    user: 2,
    dumb: 3
  }

  has_many :contacts

  def self.role_ids_i18n
    role_ids.map do |key, value|
      [I18n.t("enums.#{model_name.i18n_key}.role_id.#{key}"), key]
    end
  end

  def admin?
    self.role_id == "admin"
  end

  def user?
    self.role_id == "user"
  end

  def dumb?
    self.role_id == "dumb"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
#  before_action :set_paper_trail_whodunnit
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:error] = t('app.access_errors.not_allowed')
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @q = Contact.ransack(params[:q])
    @contacts = @q.result.order(:name).page(params[:page]).per(10)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    authorize @contact
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    authorize @contact
  end

  # GET /contacts/1/edit
  def edit
    authorize @contact
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params.merge({ user_id: current_user.id}))
    authorize @contact

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      authorize @contact
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    authorize @contact
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(
        :avatar,
        :name,
        :email,
        :cellphone,
        :address,
        :birthdate)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(:email).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def edit
    authorize @user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'user was successfully created.'
    else
      render :new
    end
  end

  def show

  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'Contact was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def handle_field(field)
    field.blank? ? "n/d" : field
  end

  def header(title, path)
    header_title = content_tag :div, class: "col-md-6" do
              content_tag :h4, title
            end

    button = (
      content_tag :div, class: "col-md-6 text-right" do
        link_to t("app.new", name: title), path, class: "btn btn-success"
      end
    )
    content_tag :div, class: "well row" do
      concat(header_title)
      concat(button)
    end
  end

  def bootstrap_class_for flash_type
    type = {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }

    type[flash_type.to_sym]
  end

  def messages
    flash.each do |msg_type, message|
      concat(
        content_tag(:div, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
          concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
          concat message
        end
      )
    end

    nil
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :birthdate %>
    <%= f.text_field :birthdate, id: 'dataNasc', class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :cellphone %>
    <%= f.text_field :cellphone, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<%= search_form_for @q do |f| %>
  <div class="row">
    <div class="col-md-10">
      <%= f.search_field :name_cont, class: "form-control", placeholder: t('views.contacts.search_placeholder') %>
    </div>

    <div class="col-md-2">
      <%= button_tag type: "submit", class: "btn btn-success" do %>
        <%= fa_icon("search") %>
      <% end %>
      <%= link_to contacts_path, class: "btn btn-danger" do %>
        <%= fa_icon("close") %>
      <% end %>
    </div>
  </div>
<% end %>

<h1><%= t("activerecord.models.contact") %></h1>

<%= link_to t("app.new", name: t("activerecord.models.contact")), new_contact_path, class: "btn btn-success" %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th><%= t("activerecord.attributes.contact.name") %></th>
      <th><%= t("activerecord.attributes.contact.birthdate") %></th>
      <th><%= t("activerecord.attributes.contact.address") %></th>
      <th><%= t("activerecord.attributes.contact.email") %></th>
      <th><%= t("activerecord.attributes.contact.cellphone") %></th>
      <th><%= t("activerecord.attributes.contact.user_id") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td>
          <%= image_tag contact.avatar.url, class: "image-index" unless contact.avatar.blank? %>
        </td>
        <td><%= contact.name %></td>
        <td><%= contact.birthdate %></td>
        <td><%= contact.address %></td>
        <td><%= contact.email %></td>
        <td><%= contact.cellphone %></td>
        <td><%= contact.user.name unless contact.user.blank? %></td>
        <td><%= link_to fa_icon("eye"), contact, class: "btn btn-primary" %></td>
        <td><%= link_to fa_icon("pencil-square-o"), edit_contact_path(contact), class: "btn btn-primary" %></td>
        <td><%= link_to fa_icon("trash"), contact, class: "btn btn-danger",method: :delete, data: { confirm: t('app.messages.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div>
  <%= paginate @contacts %>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <%= image_tag @contact.avatar.url, class: "image-show" unless @contact.avatar.blank? %>
</p>
<p>
  <strong><%= t("activerecord.attributes.contact.name") %>:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong><%= t("activerecord.attributes.contact.birthdate") %>:</strong>
  <%= @contact.birthdate %>
</p>

<p>
  <strong><%= t("activerecord.attributes.contact.address") %>:</strong>
  <%= @contact.address %>
</p>

<p>
  <strong><%= t("activerecord.attributes.contact.email") %>:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong><%= t("activerecord.attributes.contact.cellphone") %>:</strong>
  <%= @contact.cellphone %>
</p>

<p>
  <strong><%= t("activerecord.attributes.contact.user_id") %>:</strong>
  <%= @contact.user.name %>
</p>
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_menu.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><%= t("app.appname") %></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to t("activerecord.models.contact"), contacts_path %>
          </li>
          <% if policy(User).edit? %>
          <li>
            <%= link_to t("activerecord.models.user"), users_path %>
          </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href=""><%= current_user.name %></a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= t("app.menu") %><span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("app.logout"), destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("app.appname") %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/menu" %>
    <div class="container">
      <%= messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

    <div class="form-group">
      <%= f.label :role_id %>
      <%= f.select :role_id, options_for_select(User.role_ids_i18n), class: "form-control" %>
    </div>

  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Editar Usuário</h1>

<%= render 'form', user: @user %>

<hr/>

<div class="text-right">
  <%= link_to 'Show', @user, class: "btn btn-success" %>
  <%= link_to 'Back', users_path, class: "btn btn-success"  %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<%= header(t("activerecord.models.user"), new_user_path)%>


<table class="table">
  <thead>
    <tr>
      <th><%= t("activerecord.attributes.user.name") %></th>
      <th><%= t("activerecord.attributes.user.email") %></th>
      <th><%= t("activerecord.attributes.user.role_id") %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= handle_field(user.name) %></td>
        <td><%= user.email %></td>
        <td><%= handle_field(user.role_id_i18n) %></td>
        <td class="text-right">
          <%= link_to t('app.show'), user, class: "btn btn-primary" %>
          <%= link_to t('app.edit'), edit_user_path(user), class: "btn btn-primary" %>
          <%= link_to t('app.destroy'), user, class: "btn btn-danger",method: :delete, data: { confirm: t('app.messages.are_you_sure') } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<div>
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= t("activerecord.attributes.user.name") %>:</strong>
  <%= handle_field(@user.name) %>
</p>
<p>
  <strong><%= t("activerecord.attributes.user.email") %>:</strong>
  <%= handle_field(@user.email) %>
</p>
<p>
  <strong><%= t("activerecord.attributes.user.role_id") %>:</strong>
  <%= handle_field(@user.role_id_i18n) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>